# Generated by Django 2.1.2 on 2021-03-25 02:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='cmr_no',
            field=models.TextField(blank=True, null=True, verbose_name='Resin grade'),
        ),
        migrations.AddField(
            model_name='item',
            name='color_shade',
            field=models.TextField(blank=True, null=True, verbose_name='color_shade'),
        ),
        migrations.AddField(
            model_name='item',
            name='customer_name',
            field=models.TextField(blank=True, null=True, verbose_name='Customer company name'),
        ),
        migrations.AddField(
            model_name='item',
            name='requester_name',
            field=models.TextField(blank=True, null=True, verbose_name='Requester person name'),
        ),
    ]
